-- MySQL Script generated by MySQL Workbench
-- ter 21 mai 2019 22:24:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_inventario` DEFAULT CHARACTER SET latin1 ;
USE `sistema_inventario` ;

-- -----------------------------------------------------
-- Table `sistema_inventario`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`cargos` (
  `id_cargo` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`estados` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`cidades` (
  `id_cidade` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_estado` INT(11) NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_cidades_estados1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `sistema_inventario`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`pessoas` (
  `id_pessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `id_cidade` INT(11) NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  INDEX `fk_pessoas_cidades1_idx` (`id_cidade` ASC),
  CONSTRAINT `fk_pessoas_cidades1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `sistema_inventario`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`coordenadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`coordenadores` (
  `id_coordenador` INT(11) NOT NULL,
  `id_pessoa` INT(11) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_coordenador`),
  INDEX `fk_coordenadores_pessoas1_idx` (`id_pessoa` ASC),
  CONSTRAINT `fk_coordenadores_pessoas1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `sistema_inventario`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`setores` (
  `id_setor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_coordenador` INT(11) NOT NULL,
  `ramal_telefonico` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_setor`),
  INDEX `fk_setores_coordenadores1_idx` (`id_coordenador` ASC),
  CONSTRAINT `fk_setores_coordenadores1`
    FOREIGN KEY (`id_coordenador`)
    REFERENCES `sistema_inventario`.`coordenadores` (`id_coordenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`funcionarios` (
  `id_funcionario` INT(11) NOT NULL,
  `id_pessoa` INT(11) NOT NULL,
  `id_cargo` INT(11) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_setor` INT(11) NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionarios_pessoas1_idx` (`id_pessoa` ASC),
  INDEX `fk_funcionarios_cargos1_idx` (`id_cargo` ASC),
  INDEX `fk_funcionarios_setores1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_funcionarios_cargos1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `sistema_inventario`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_pessoas1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `sistema_inventario`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_setores1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `sistema_inventario`.`setores` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`emprestimos` (
  `id_emprestimo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_funcionário` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `data_devolucao` DATETIME NOT NULL,
  `observacao` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimos_funcionarios1_idx` (`id_funcionário` ASC),
  CONSTRAINT `fk_emprestimos_funcionarios1`
    FOREIGN KEY (`id_funcionário`)
    REFERENCES `sistema_inventario`.`funcionarios` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'COLUNA STATUS PARA CONTROLAR SITUACAO EMPRESTIMO';


-- -----------------------------------------------------
-- Table `sistema_inventario`.`devolucoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`devolucoes` (
  `id_devolucao` INT(11) NOT NULL AUTO_INCREMENT,
  `id_emprestimo` INT(11) NOT NULL,
  `data` DATETIME NOT NULL,
  `observacao` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_devolucao`),
  INDEX `fk_devolucoes_emprestimos1_idx` (`id_emprestimo` ASC),
  CONSTRAINT `fk_devolucoes_emprestimos1`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `sistema_inventario`.`emprestimos` (`id_emprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'COLUNA STATUS PARA CONTROLE DO QUE FOI DEVOLVIDO';


-- -----------------------------------------------------
-- Table `sistema_inventario`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`itens` (
  `id_item` INT(11) NOT NULL AUTO_INCREMENT,
  `id_setor` INT(11) NOT NULL,
  `matricula` VARCHAR(25) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(100) NOT NULL,
  `data_aquisicao` DATETIME NOT NULL,
  `valor_aquisicao` INT(11) NOT NULL,
  `vida_util` DATETIME NOT NULL,
  `descricao_estado` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_itens_setores1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_itens_setores1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `sistema_inventario`.`setores` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'COLUNA SITUACAO PARA CONTROLE SE ESTA DISPONIVEL OU EMPRESTADO';


-- -----------------------------------------------------
-- Table `sistema_inventario`.`itens_devolucoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`itens_devolucoes` (
  `id_devolucao` INT(11) NOT NULL,
  `id_item` INT(11) NOT NULL,
  PRIMARY KEY (`id_devolucao`, `id_item`),
  INDEX `fk_devolucoes_has_itens_itens1_idx` (`id_item` ASC),
  INDEX `fk_devolucoes_has_itens_devolucoes1_idx` (`id_devolucao` ASC),
  CONSTRAINT `fk_devolucoes_has_itens_devolucoes1`
    FOREIGN KEY (`id_devolucao`)
    REFERENCES `sistema_inventario`.`devolucoes` (`id_devolucao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devolucoes_has_itens_itens1`
    FOREIGN KEY (`id_item`)
    REFERENCES `sistema_inventario`.`itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistema_inventario`.`itens_emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_inventario`.`itens_emprestimos` (
  `id_emprestimo` INT(11) NOT NULL,
  `id_item` INT(11) NOT NULL,
  PRIMARY KEY (`id_emprestimo`, `id_item`),
  INDEX `fk_emprestimos_has_itens_itens1_idx` (`id_item` ASC),
  INDEX `fk_emprestimos_has_itens_emprestimos1_idx` (`id_emprestimo` ASC),
  CONSTRAINT `fk_emprestimos_has_itens_emprestimos1`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `sistema_inventario`.`emprestimos` (`id_emprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimos_has_itens_itens1`
    FOREIGN KEY (`id_item`)
    REFERENCES `sistema_inventario`.`itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
